name: prod

services:
  userbot:
    build: .
    container_name: ai-userbot-app
    restart: on-failure
    command: ["python", "-m", "main"]
    env_file: .env
    depends_on:
      - db  # Ждем запуска БД перед стартом userbot
    ports:
      - "8000:8000"
    healthcheck:
      # Используем curl для проверки нашего эндпоинта
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthz" ]

      # Интервалы настроены так, чтобы не дергать сервис слишком часто,
      # но быстро реагировать на зависания
      interval: 30s       # Проверка каждые 30 секунд
      timeout: 5s         # Если ответа нет 5 сек — считаем попытку неудачной
      retries: 3          # 3 неудачи подряд = статус unhealthy -> перезапуск
      start_period: 60s

  db:
    image: postgres:16-alpine
    container_name: ai-userbot-db
    restart: unless-stopped
    env_file: .env
#    environment:
#      POSTGRES_USER: ${DB_USER:-userbot}
#      POSTGRES_PASSWORD: ${DB_PASSWORD:-userbot_password}
#      POSTGRES_DB: ${DB_NAME:-userbot_db}
    ports:
      - "5432:5432"  # Опционально — только если нужен доступ снаружи
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: